apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: cloudwatch-exporter
  labels:
    k8s-app: cloudwatch-exporter
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: prometheus-cloudwatch-exporter 
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: sqs-metrics
    interval: 30s
